import pandas as pd
import numpy as np
import logging

# --- Configuration ---
logging.basicConfig(level=logging.INFO, format='[REDACTED_BY_SCRIPT]')

# This list defines all the 'distance to nearest' columns that will be checked
# to find the overall minimum distance to any environmental constraint.
# These columns are expected to be generated by their respective upstream executors.
DISTANCE_COLUMNS = [
    'aw_dist_to_nearest_m',
    'aonb_dist_to_nearest_m',
    'sssi_dist_to_nearest_m',
    'sssi_unit_dist_to_nearest_m',
    'np_dist_to_nearest_m',
    'sac_dist_to_nearest_m',
    'spa_dist_to_nearest_m',
    'alc_dist_to_nearest_m',
    'nt_dist_to_nearest_m',
    '[REDACTED_BY_SCRIPT]',
    'hp_dist_to_nearest_m',
    'ph_dist_to_nearest_m',
    '[REDACTED_BY_SCRIPT]',
]

# This map defines the columns to be summed for creating 'count of constraints' features.
# The key is the radius (in meters), and the value is a list of column name patterns.
COUNT_COLUMNS_MAP = {
    2000: [
        'aw_AWP_count_in_2km', 'aonb_count_in_2km', 'sssi_count_in_2km',
        'np_count_in_2km', 'sac_count_in_2km', 'spa_count_in_2km',
        'hp_count_in_2km', 'ph_count_in_2km'
    ],
    5000: [ # For European designations
        'sac_count_in_5km', 'spa_count_in_5km'
    ]
}

# Map for identifying the dominant constraint type based on the nearest feature.
DOMINANT_CONSTRAINT_MAP = {
    'aw_dist_to_nearest_m': 'AncientWoodland',
    'aonb_dist_to_nearest_m': 'AONB',
    'sssi_dist_to_nearest_m': 'SSSI',
    'np_dist_to_nearest_m': 'NationalPark',
    'sac_dist_to_nearest_m': 'SAC',
    'spa_dist_to_nearest_m': 'SPA',
    'hp_dist_to_nearest_m': 'HistoricParkland',
    'ph_dist_to_nearest_m': 'PriorityHabitat',
    'nt_dist_to_nearest_m': 'NationalTrail',
}


def calculate_minimum_distance(df, distance_cols):
    """[REDACTED_BY_SCRIPT]"""
    logging.info("[REDACTED_BY_SCRIPT]")
    
    existing_cols = [col for col in distance_cols if col in df.columns]
    if not existing_cols:
        logging.warning("[REDACTED_BY_SCRIPT]'env_min_dist_to_any_constraint_m'. Skipping.")
        df['[REDACTED_BY_SCRIPT]'] = np.nan
        return df

    # Calculate the row-wise minimum, ignoring NaNs
    df['[REDACTED_BY_SCRIPT]'] = df[existing_cols].min(axis=1, skipna=True)
    logging.info("Successfully calculated 'env_min_dist_to_any_constraint_m'.")
    return df

def calculate_constraint_counts(df, count_map):
    """[REDACTED_BY_SCRIPT]"""
    logging.info("[REDACTED_BY_SCRIPT]")

    # Count for 2km radius
    radius_2km_cols = count_map.get(2000, [])
    existing_2km_cols = [col for col in radius_2km_cols if col in df.columns]
    if existing_2km_cols:
        df['[REDACTED_BY_SCRIPT]'] = df[existing_2km_cols].sum(axis=1, skipna=True)
        logging.info("Successfully calculated 'env_count_of_constraints_in_2km'.")
    else:
        logging.warning("[REDACTED_BY_SCRIPT]'env_count_of_constraints_in_2km'.")
        df['[REDACTED_BY_SCRIPT]'] = 0

    # Count for European designations at 5km
    radius_5km_euro_cols = count_map.get(5000, [])
    existing_5km_euro_cols = [col for col in radius_5km_euro_cols if col in df.columns]
    if existing_5km_euro_cols:
        df['[REDACTED_BY_SCRIPT]'] = df[existing_5km_euro_cols].sum(axis=1, skipna=True)
        logging.info("Successfully calculated 'env_count_of_european_designations_in_5km'.")
    else:
        logging.warning("[REDACTED_BY_SCRIPT]")
        df['[REDACTED_BY_SCRIPT]'] = 0
        
    return df

def determine_dominant_constraint(df, dominant_map):
    """[REDACTED_BY_SCRIPT]"""
    logging.info("[REDACTED_BY_SCRIPT]")
    
    existing_dist_cols = {k: v for k, v in dominant_map.items() if k in df.columns}
    if not existing_dist_cols:
        logging.warning("[REDACTED_BY_SCRIPT]")
        df['[REDACTED_BY_SCRIPT]'] = 'None'
        return df

    # Find the column name with the minimum distance for each row
    s_min_dist_col = df[existing_dist_cols.keys()].idxmin(axis=1)
    
    # Map the column name to the constraint type
    df['[REDACTED_BY_SCRIPT]'] = s_min_dist_col.map(existing_dist_cols).fillna('None')
    logging.info("[REDACTED_BY_SCRIPT]")
    return df

def calculate_sic_metrics(df):
    """
    Placeholder function to calculate Strategic Influence Corridor (SIC) metrics.
    The logic for these features is complex and likely depends on a combination of
    environmental, planning, and infrastructure data.
    """
    logging.info("[REDACTED_BY_SCRIPT]")
    # This is a placeholder. The actual logic would be complex.
    # For now, we will add the columns with null values.
    df['[REDACTED_BY_SCRIPT]'] = np.nan
    df['[REDACTED_BY_SCRIPT]'] = np.nan
    logging.warning("'SIC_Corridor_Intensity' and 'SIC_Urban_Fringe_Pressure'[REDACTED_BY_SCRIPT]")
    return df


def execute(master_gdf):
    """
    Main execution function for the environmental synthesis module.
    This executor should run AFTER all individual environmental executors.
    It ensures the 'hex_id' index is preserved throughout the operation.
    """
    logging.info("[REDACTED_BY_SCRIPT]")

    # Ensure hex_id is the index for alignment.
    if master_gdf.index.name != 'hex_id':
        if 'hex_id' in master_gdf.columns:
            master_gdf.set_index('hex_id', inplace=True)
        else:
            logging.error("Critical error: 'hex_id'[REDACTED_BY_SCRIPT]")
            raise KeyError("'hex_id'[REDACTED_BY_SCRIPT]")

    # Work on a copy to avoid modifying the original DataFrame unexpectedly.
    df = master_gdf.copy()

    # The helper functions operate on the DataFrame and add columns, preserving the index.
    df = calculate_minimum_distance(df, DISTANCE_COLUMNS)
    df = calculate_constraint_counts(df, COUNT_COLUMNS_MAP)
    df = determine_dominant_constraint(df, DOMINANT_CONSTRAINT_MAP)
    df = calculate_sic_metrics(df)

    logging.info("[REDACTED_BY_SCRIPT]")
    
    # The returned DataFrame 'df' is a GeoDataFrame with the new columns and hex_id as the index.
    return df
